### ISSUE TITLE
arttime in exchange of cdecl

### ISSUE THREAD

**Issue by reportaman** [paul-j-lucas/cdecl#21]
Thanks for having this project, not sure why it's not as popular yet. 

In spirit of open source barter trade, consider my recent project https://github.com/reportaman/arttime as a token of appreciation. Sorry, couldn't send it as an email as there is no email listed on your GitHub account (like mine).

**Comment by paul-j-lucas** [comment]
> Thanks for having this project.

You're welcome.

> In spirit of open source barter trade, consider my recent project https://github.com/reportaman/arttime as a token of appreciation.

Thanks, I guess, but:

1. I do this with no expectation of any trade.
2. Your project isn't something I'm interested in.

> Sorry, couldn't send it as an email as there is no email listed on your GitHub account.

Yes, and that's intentional.

> (like mine).

Your account lists no e-mail address.

Again, thanks; but please don't respond to this.  In the future, please use issue reporting **_only_** for reporting actual issues with cdecl. Thanks.
