### ISSUE TITLE
Support for alternative FLEX and YACC implementations?

### ISSUE THREAD

**Issue by Flowdalic** [paul-j-lucas/cdecl#27]
cdecl currently checks for flex providing the LEX implementation

https://github.com/paul-j-lucas/cdecl/blob/c3d7878aa6734e084c0ef0e03ae91378378bf8d2/configure.ac#L58-L62

and bison providing the YACC implementation

https://github.com/paul-j-lucas/cdecl/blob/c3d7878aa6734e084c0ef0e03ae91378378bf8d2/configure.ac#L63-L67

due packaging cdecl in Gentoo, the question came up how far cdecl supports alternative implementations (Gentoo (bug # 879233)[https://bugs.gentoo.org/879233]). Namely reflex and byacc.

Is the hard dependency on flex and bison deliberate, or is the strong check in configure.ac via AX_PROG_FLEX / AX_PROG_BISON unintentional and could be replaced with AC_PROG_LEX / AC_PROG_YACC?

**Comment by paul-j-lucas** [comment]
I haven't ever used any alternative implementations.  I have no idea whether `reflex` or `byacc` would work.  You're free to try it and see.  If the answer is yes, you're welcome to submit a pull request.

I don't think you can simply use `AC_PROG_LEX` and `AC_PROG_YACC` because those would also erroneously allow vanilla `lex` and `yacc` and those definitely do _not_ work.

**Comment by paul-j-lucas** [comment]
Closing since no response from originator.
